---

- name: Install cron
  apt:
    pkg: '{{ item }}'
    cache_valid_time: 86400
  with_items:
    - cron
    - mktemp
    - openssl

- name: Install script
  copy:
    src: 'sslcertcheck.sh'
    dest: '{{ monit_sslcertcheck_script }}'
    owner: root
    group: root
    mode: '0755'

- name: Install monit helper
  copy:
    src: 'monit-helper.sh'
    dest: '/usr/bin/sslcertcheck-monit-helper.sh'
    owner: root
    group: root
    mode: '0755'
